[versions]
kotlin = "2.1.0"
kotlinx-coroutines = "1.9.0"
kotlinx-datetime = "0.6.1"
kotlinx-serialization = "1.7.3"
ktor = "2.3.13"
bitcoinkmp = "0.21.0" # when upgrading bitcoin-kmp, keep secpjnijvm in sync!
secpjnijvm = "0.16.0"
kermit = "2.0.4"
slf4j = "1.7.36"

# test dependencies
test-kodein-memory = "0.12.0"
test-bouncycastle = "1.64"
test-logback = "1.2.3"
test-sqlitejdbc = "3.32.3.3"

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
