name: Check

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - '.github/**'
      - '!.github/workflows/test.yml'
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - '.github/**'
      - '!.github/workflows/test.yml'

jobs:

  upload:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ]
    steps:

      # 1 - checkout repositories
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Checkout kodein-log with UTC fork
        uses: actions/checkout@v2
        with:
          repository: dpad85/Kodein-Log
          ref: utc-timezone
          path: kodein-log

      # 2 - setup cache and tools
      - name: Cached Konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Cached Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Install curl
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -y
          sudo apt install -y libcurl4-gnutls-dev
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # 3 - build dependencies
      - name: Build kodein-log and publish it to local maven
        run: |
          cd kodein-log
          ./gradlew publishToMavenLocal

      # 4 - tests
      - name: Check with integration
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew check -PintegrationTests=include -PverboseTests=ON
      - name: Check without integration
        if: matrix.os != 'ubuntu-latest'
        run: ./gradlew check -PverboseTests=ON
